### ISSUE TITLE
Support for non Openstack services

### ISSUE THREAD

**Issue by malini-kamalambal** [rackerlabs/mimic#108]
Currently any non Openstack API will need to go to resource.py (See example https://github.com/rackerlabs/mimic/pull/107/files). In the long run this can cause the resource.py to grow huge. Need a better solution to handle this.

**Comment by glyph** [comment]
Proposal: let's have a new plugin API which uses a fixed URL - let's say `/mimicking/external/` - and then your plugin declares a namespace under there it wants to claim.

Since most "outside the service catalog" APIs are associated with a specific provider, or at least a piece of software, in order to avoid conflicts, let's use full domain names as the recommended string for the plugin.

So, for example, if someone wanted to write a Stripe mock, they would write an `IExternalAPIMock` plugin, which would have an `api_domain` attribute of `"api.stripe.com"`, and then its root resource would show up as `http://localhost:8900/mimicking/external/api.stripe.com/` and it could then have a `@route("/v1")` and so on dispatching down from there.

**Comment by glyph** [comment]
(That example domain taken from https://stripe.com/docs/api )

**Comment by glyph** [comment]
This should also log a message at startup listing all the external URLs that are loaded; see #69 .

**Comment by glyph** [comment]
Since we already have several hard-coded top-level non-openstack services, we should continue to support both paths for a few releases before deleting the existing ones.

**Comment by glyph** [comment]
In the case of a conflict between two namespaces (we might have two separate external implementations of the stripe API, for example) we should just log an error message about the conflict and let one "win".
