### ISSUE TITLE
Tox uses a different version of lint, doc, docspell requirements compared to what in dev-requirements

### ISSUE THREAD

**Issue by lekhajee** [rackerlabs/mimic#199]
Possibly create different requirements files for lint, doc, docspell and use the `deps = -r{toxinidir}/lint-requirements.txt` and such

**Comment by glyph** [comment]
A couple of thoughts:

- Put all the requirements into a `requirements` directory, then we can have  `requirements/run.txt`, `requirements/lint.txt`, `requirements/dev.txt`, `requirements/all.txt` and not clutter up the top level directory.
- Any requirements which require other requirements (development requires running, for example) can use `-r other-requirements.txt`
- Each requirements file should have a comment at the top saying what exactly you need it for.

**Comment by glyph** [comment]
When installing Mimic itself, we have two use-cases.

One is to deploy on exact, known versions of everything - which is what our continuous infrastructure should be doing; generally pinning everything.  These exact versions of dependencies should go in `requirements.txt` and should be updated explicitly by pull request when they become outdated.  I just set up requires.io for this project, so we can start to get visibility into that: https://requires.io/github/rackerlabs/mimic/requirements/?branch=master

Another is to deploy on an abstract, constrained set of requirements, which is what our `setup.py` should be doing.  `setup.py` should be abstract, even if we don't test every possible supported configuration, because we may have users who want or need to install mimic into the same environment as other things with higher version requirements, and we shouldn't prohibit that.

**Comment by glyph** [comment]
When installing mimic's development dependencies, we want to have a single source of truth which you can pull from for random development command-line stuff.  Right now there is `dev-requirements.txt` as well as various sections in `tox.ini`.

**Comment by glyph** [comment]
I just turned on automatic pull requests on requires.io… hopefully that means we'lll see an automatic PR come in soon that updates our dependencies.

**Comment by glyph** [comment]
#497 attempts to address this.

**Comment by glyph** [comment]
I think #497 actually addressed these problems reasonably well.

**Comment by glyph** [comment]
Feel free to reopen if someone disagrees, but I guess I will proactively close this :)
