### ISSUE TITLE
Changes-since for nova server details

### ISSUE THREAD

**Issue by cyli** [rackerlabs/mimic#252]
http://docs.rackspace.com/servers/api/v2/cs-devguide/content/ChangesSince.html

**Comment by manishtomar** [comment]
To do this, mimic will need to keep list of deleted servers. And delete them after 30 days. This can cause lot of memory usage if mimic instance is used to run many tests. Is this acceptable?

**Comment by glyph** [comment]
We have no performance metrics, so, "yes".  If we want to care about memory we need a memory benchmark ;-). We may add some persistence later so we can get more of these servers out of memory.  Or we can add a "purge" control plane endpoint to clean up a tenant (since all state is local to a tenant).
