### ISSUE TITLE
Flakey mimic test discovered while working on PR.

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/mimic#276]
Flakey mimic test.

```
    def test_different_tenants_same_region_different_lbs(self):
        """
        Creating a LB for one tenant in a particular region should not
        create it for other tenants in the same region.
        """
        self._create_loadbalancer()

        other_tenant = TenantAuthentication(self, self.root, "other", "other")

        list_lb_response, list_lb_response_body = self.successResultOf(
            request_with_content(
                self, self.root, "GET",
                other_tenant.nth_endpoint_public(0) + "/loadbalancers"))

#        print("URL({})".format(other_tenant.nth_endpoint_public(0)+"/loadbalancers"))
        self.assertEqual(list_lb_response.code, 200)
```

If you leave the print statement commented out, or remove it all-together, this test fails.

If you **uncomment** the print statement, at least for me, the test passes.

This test exercises code which I have not touched in my PR at #274 .

**Comment by sam-falvo** [comment]
So, I perhaps fixed it with the help of @cyli 's comments, where I added `loadbalancer_plugin.loadbalancer_control` to test_core.py.

However, I would still like to know why this change was even relevant.  I just don't see how these two pieces of code relate.

Thanks!

**Comment by sam-falvo** [comment]
OK, change definitely did not fix issue.  The test is failing again for me, and I changed nothing since my last update here.

**Comment by glyph** [comment]
Can you update with the traceback describing the failure?

**Comment by glyph** [comment]
I don't think that this test is "flakey" in the sense of non-deterministic, because after running with `trial`'s `--until-failure` option, I never saw a failure, and I let it run for 12,000 consecutive test runs:

```
Test Pass 12076
mimic.test.test_loadbalancer
  LoadbalancerAPITests
    test_different_tenants_same_region_different_lbs ...                   [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.007s

PASSED (successes=1)
Test Pass 12077
```

However, it *is* "flakey" in the sense of "fragile" - `nth_endpoint_public` is a terrible API we should eliminate, which depends on random accidents of plugin ordering and while it should work reliably, if you do anything to disturb the fragile structure of the test's setup, you will start seeing spurious failures. So I wouldn't call this invalid nonetheless.
