### ISSUE TITLE
Feature Request: Pilot API (Reach Shared Header)

### ISSUE THREAD

**Issue by ksheedlo** [rackerlabs/mimic#342]
Pilot is the shared header from Reach that Intelligence fetches through the Pilot API. I'd like to have this in Mimic so that we don't depend on the real API in testing and for offline use.

http://docs.pilot.rackspace.net/getting-started.html

This API is not currently in Rackspace service catalogs and probably won't be ever, but it does use Keystone token-based authentication. I suppose putting it in Mimic means putting it in the catalog as opposed to having a static endpoint. This will complicate client code wanting to do things The Right Way, but in practice we may try to cheat a bit and hard-code the leading part of the endpoint in our application. Thoughts?

**Comment by ksheedlo** [comment]
discussed in person with @glyph - we will build out the plugin and put it into the service catalog. The application will try loading the endpoint from the catalog and fall back to the configured Pilot endpoint.

**Comment by glyph** [comment]
Just to recap some of the points made in that in-person discussion so that the community is privy to them:

This is an internal API, and normally Mimic's design principles have it just do whatever the "real" APIs do; for example, in the case of something like Fastly or Noit, we have the APIs exposed at `/` because software that talks to them expects to configure a root URL.

This is a bit of a special case though; since it takes the auth token, it behaves sort of *as if* you'd discovered it via a service catalog; the software that needs to configure it (the cloud control panel, cloud intelligence) currently hard-codes it because there's only one API endpoint, so it would need to add *new* configuration either way, it doesn't have an existing way of configuring it in concert with the identity API it's talking to.

Given that, the choice seems to be "put it at the root, treat it as a weird external plugin, and add more configuration on the client side", or, "put it in the catalog with a special mimic identifier, and have the clients just look for it there".  Since the latter strategy allows us to avoid any additional configuration logic and have mimic be automagical for clients, it seems like that's a better call even if the service doesn't have a real, public service catalog identifier.

**Comment by ksheedlo** [comment]
Following up on this: Intelligence ended up needing a fallback in case both the default header and API response fail to load. The fallback will also be our strategy for offline and isolated testing. I'm closing this feature request, as I don't think it's really needed in Mimic.
