### ISSUE TITLE
openstack cli client (python-openstackclient) support?

### ISSUE THREAD

**Issue by nyasukun** [rackerlabs/mimic#509]
I suppose there are many application using ostack referring python-openstackclient implementation.
However currently this cli client failed to use for mimic as following:
```
# nova list
No handlers could be found for logger "keystoneauth.identity.generic.base"
ERROR (DiscoveryFailure): Could not determine a suitable URL for the plugin
```

this is caused by there is no resource at /identiy/v2.0.
As I put a resource definition at this point experimentally, mimic responds error after this interaction.

Does this project include openstack cli client (python-openstackclient) as a scope?
If no, let me ask a request to make python-openstackclient works.

**Comment by glyph** [comment]
> Does this project include openstack cli client (python-openstackclient) as a scope?

Absolutely. In fact, we should really have an integration test that installs `python-openstackclient` into a virtualenv.

**Comment by glyph** [comment]
To be clear, in the past, Mimic did work with the openstack nova client; there is a screencast in https://lekhajee.github.io/mimic-workshop/ that demonstrates it working.  It is intended to.  I strongly suspect that an older version will work; but, of course, since we don't have test coverage for it, it broke.

**Comment by nyasukun** [comment]
Thanks for reply.
So when we find a something wrong with ```python-openstackclient```, we can submit issues and fix them.

My question is cleared and I close this issue.
I reported identity version details issue as #511.

**Comment by Benjamin91300** [comment]
Hi there, 

I have implemented the missing ressource at at /identiy/v2.0 and also the same for nova /compute/v2 for my need.
Now, keystone and nova CLI works against mimic.

Would you be interested if I commit it ?

**Comment by BenjamenMeyer** [comment]
@Benjamin91300 PRs are always welcome

**Comment by coder-athi** [comment]
2019-10-04 03:45:14,604 - ERROR - No handlers could be found for logger "keystoneauth.identity.generic.base"
ERROR (ConnectFailure): Unable to establish connection to https://10.0.2.4:5000/v3/auth/tokens: HTTPSConnectionPool(host='10.0.2.4', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fec55ee90d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
 I am getting this error . how can i resolve this?

**Comment by coder-athi** [comment]
@Benjamin91300 Could you please help ?
